"""add passenger and add admin tables

Revision ID: 0d35c4926675
Revises: a1b2c3d4e5f6
Create Date: 2026-04-12 18:42:07.559126

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0d35c4926675"
down_revision: str | None = "a1b2c3d4e5f6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "device_tokens",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("token", sa.String(length=512), nullable=False),
        sa.Column("platform", sa.String(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token"),
    )
    op.create_index(op.f("ix_device_tokens_id"), "device_tokens", ["id"], unique=False)
    op.create_index(op.f("ix_device_tokens_user_id"), "device_tokens", ["user_id"], unique=False)
    op.create_table(
        "payments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("reservation_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("provider_payment_id", sa.String(length=128), nullable=False),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["reservation_id"], ["reservations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_payments_id"), "payments", ["id"], unique=False)
    op.create_index(
        op.f("ix_payments_provider_payment_id"), "payments", ["provider_payment_id"], unique=True
    )
    op.create_index(
        op.f("ix_payments_reservation_id"), "payments", ["reservation_id"], unique=False
    )
    op.create_index(op.f("ix_payments_user_id"), "payments", ["user_id"], unique=False)
    op.create_table(
        "trip_feedback",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("reservation_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("rating", sa.Integer(), nullable=False),
        sa.Column("packing_helpful", sa.Boolean(), nullable=False),
        sa.Column("missing_items", sa.Text(), nullable=True),
        sa.Column("comments", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["reservation_id"], ["reservations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_trip_feedback_id"), "trip_feedback", ["id"], unique=False)
    op.create_index(
        op.f("ix_trip_feedback_reservation_id"), "trip_feedback", ["reservation_id"], unique=False
    )
    op.create_index(op.f("ix_trip_feedback_user_id"), "trip_feedback", ["user_id"], unique=False)
    op.create_table(
        "trip_todos",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("reservation_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("category", sa.String(length=32), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("priority", sa.String(length=32), nullable=False),
        sa.Column("is_completed", sa.Boolean(), nullable=False),
        sa.Column("due_date", sa.Date(), nullable=True),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["reservation_id"], ["reservations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_trip_todos_id"), "trip_todos", ["id"], unique=False)
    op.create_index(
        op.f("ix_trip_todos_reservation_id"), "trip_todos", ["reservation_id"], unique=False
    )
    op.create_index(op.f("ix_trip_todos_user_id"), "trip_todos", ["user_id"], unique=False)
    op.drop_constraint(op.f("admins_user_id_key"), "admins", type_="unique")
    op.drop_index(op.f("ix_admins_user_id"), table_name="admins")
    op.create_index(op.f("ix_admins_user_id"), "admins", ["user_id"], unique=True)
    op.add_column(
        "airports", sa.Column("latitude", sa.Numeric(precision=10, scale=7), nullable=True)
    )
    op.add_column(
        "airports", sa.Column("longitude", sa.Numeric(precision=10, scale=7), nullable=True)
    )
    op.add_column("airports", sa.Column("terminal_info", sa.JSON(), nullable=True))
    op.add_column("airports", sa.Column("amenities", sa.JSON(), nullable=True))
    op.add_column("airports", sa.Column("map_url", sa.String(length=500), nullable=True))
    op.drop_constraint(op.f("passengers_user_id_key"), "passengers", type_="unique")
    op.drop_index(op.f("ix_passengers_user_id"), table_name="passengers")
    op.create_index(op.f("ix_passengers_user_id"), "passengers", ["user_id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_passengers_user_id"), table_name="passengers")
    op.create_index(op.f("ix_passengers_user_id"), "passengers", ["user_id"], unique=False)
    op.create_unique_constraint(
        op.f("passengers_user_id_key"),
        "passengers",
        ["user_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("airports", "map_url")
    op.drop_column("airports", "amenities")
    op.drop_column("airports", "terminal_info")
    op.drop_column("airports", "longitude")
    op.drop_column("airports", "latitude")
    op.drop_index(op.f("ix_admins_user_id"), table_name="admins")
    op.create_index(op.f("ix_admins_user_id"), "admins", ["user_id"], unique=False)
    op.create_unique_constraint(
        op.f("admins_user_id_key"), "admins", ["user_id"], postgresql_nulls_not_distinct=False
    )
    op.drop_index(op.f("ix_trip_todos_user_id"), table_name="trip_todos")
    op.drop_index(op.f("ix_trip_todos_reservation_id"), table_name="trip_todos")
    op.drop_index(op.f("ix_trip_todos_id"), table_name="trip_todos")
    op.drop_table("trip_todos")
    op.drop_index(op.f("ix_trip_feedback_user_id"), table_name="trip_feedback")
    op.drop_index(op.f("ix_trip_feedback_reservation_id"), table_name="trip_feedback")
    op.drop_index(op.f("ix_trip_feedback_id"), table_name="trip_feedback")
    op.drop_table("trip_feedback")
    op.drop_index(op.f("ix_payments_user_id"), table_name="payments")
    op.drop_index(op.f("ix_payments_reservation_id"), table_name="payments")
    op.drop_index(op.f("ix_payments_provider_payment_id"), table_name="payments")
    op.drop_index(op.f("ix_payments_id"), table_name="payments")
    op.drop_table("payments")
    op.drop_index(op.f("ix_device_tokens_user_id"), table_name="device_tokens")
    op.drop_index(op.f("ix_device_tokens_id"), table_name="device_tokens")
    op.drop_table("device_tokens")
    # ### end Alembic commands ###
