"""schema_fixes

Revision ID: 0d52ce81312c
Revises: 9c1f6e2a4b11
Create Date: 2026-03-31 22:56:09.933778

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "0d52ce81312c"
down_revision: str | None = "9c1f6e2a4b11"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
