"""try

Revision ID: 2bb649503229
Revises: 67b9b4b9f61c
Create Date: 2026-03-27 19:34:56.921469

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "2bb649503229"
down_revision: str | None = "67b9b4b9f61c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
