"""epic

Revision ID: 3d07861e4485
Revises: d756bc609e96
Create Date: 2026-04-06 23:19:52.571916

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = '3d07861e4485'
down_revision: str | None = 'd756bc609e96'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
