"""Epic 2

Revision ID: 60eece5c6296
Revises: 2bb649503229
Create Date: 2026-03-27 19:38:15.290847

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "60eece5c6296"
down_revision: str | None = "2bb649503229"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
