"""create-table

Revision ID: f256384d0ae8
Revises: 8f3e9a1b2c4d
Create Date: 2026-03-29 23:43:45.802096

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "f256384d0ae8"
down_revision: str | None = "8f3e9a1b2c4d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
